Update rocketship to v0.46.2
synapsestudios/devops-toolbox pull request #11
Opened 2020-10-26 23:32 UTC by jamesbrink

This fixes a breaking issue that started occurring on the interactive zsh shell

2020-10-26 23:33 UTC, spruce-bruce approved these changes

2020-10-26 23:33 UTC, spruce-bruce requested changes
CI is failing?

2020-10-27 18:35 UTC, jamesbrink commented
@spruce-bruce yeah i forgot to rebase, I had that other PR open for months 😆

2020-10-27 23:11 UTC, spruce-bruce approved these changes

2020-10-27 23:11 UTC, merged